### ISSUE TITLE
Not all series being added.

### ISSUE THREAD

**Issue by demon326** [cytec/SynoDLNAtrakt#29]
EDIT: script has issues with capital letters, but with folder name in small letters, the issue is the same.

Hello, its me again, the user that runs in to the nasty problems with this addon :D.

GoT a new issue to report, the app is not adding all of the tv-shows in the tv-folder... it only added 4 shows and what ever i do, it won't add any other, even with forced scroble, import,...

The debug log only mentions scheudles but no errors(the error wand warning log ar empty)

The folder structure for series is as follows:
/volume1/downloads/complete/TV/Almost Human/Season 01

Config file(removed user and password in paste):

```
[General]
accesslog = /var/log/lighttpd/access.log
moviedir = /volume1/downloads/complete/movie/
seriesdir = /volume1/downloads/complete/TV/
try_guessing = 1
delete_logs = 0
absolute_ep_anime = 1
hide_watched = 0
datadir = /volume1/SynoDLNAtrakt
movies_3d = 0
[Advanced]
logtoconsole = 0
debugmode = 1
min_progress = 50
interval = 60
language = en
port = 1337
```

Episode names:
Almost.Human.S01E01.Pilot.mkv
 Every episode has an *nfo file with the following structure:

```
<episodedetails xsd="http://www.w3.org/2001/XMLSchema" xsi="http://www.w3.org/2001/XMLSchema-instance">
  <title>Pilot</title>
  <season>1</season>
  <episode>1</episode>
  <aired>2013-11-17</aired>
  <plot>In the year 2048, an unprecedented increase in the crime rate has made being a cop only more dangerous than it is today, necessitating that every police officer partner with an android. John Kennex, a detective and sole survivor of a devastating police ambush, and his robot partner, Dorian, solve cases and fight to keep the lid on dangerously evolved criminals in this futuristic landscape.</plot>
  <displayseason />
  <displayepisode />
  <thumb>http://thetvdb.com/banners/episodes/267702/4566247.jpg</thumb>
  <watched>false</watched>
  <credits>J.H. Wyman</credits>
  <director>Brad Anderson</director>
  <rating>8.0</rating>
  <actor>
    <name>Karl Urban</name>
    <role>John Kennex</role>
    <thumb>http://thetvdb.com/banners/actors/312982.jpg</thumb>
  </actor>
  <actor>
    <name>Michael Ealy</name>
    <role>Dorian</role>
    <thumb>http://thetvdb.com/banners/actors/312983.jpg</thumb>
  </actor>
  <actor>
    <name>Lili Taylor</name>
    <role>Captain Sandra Maldonado</role>
    <thumb>http://thetvdb.com/banners/actors/312984.jpg</thumb>
  </actor>
  <actor>
    <name>Michael Irby</name>
    <role>Detective Richard Paul</role>
    <thumb>http://thetvdb.com/banners/actors/312987.jpg</thumb>
  </actor>
  <actor>
    <name>Minka Kelly</name>
    <role>Detective Valerie Stahl</role>
    <thumb>http://thetvdb.com/banners/actors/312986.jpg</thumb>
  </actor>
  <actor>
    <name>Mackenzie Crook</name>
    <role>Rudy Lom</role>
    <thumb>http://thetvdb.com/banners/actors/312985.jpg</thumb>
  </actor>
</episodedetails>
```

And every tv-show folder has a nfo with the following content:

```
<tvshow xsd="http://www.w3.org/2001/XMLSchema" xsi="http://www.w3.org/2001/XMLSchema-instance">
  <title>Almost Human</title>
  <rating>9.1</rating>
  <plot>The year is 2048, and the streets are as mean as ever. Fortunately, the police have a new tool in their arsenal- Synthetics, robots who are tasked with assuring the safety of the humans who created them. But not everyone is pleased with the changes. Detective John Kennex, who has been wounded in action, returns to the force and learns that his new partner is a Synthetic named Dorian. Dorian's programming is much more advanced than that of the normal Synthetic, making him seem almost human, but John still mistrusts the machine at his side. Can they work together as a team?</plot>
  <episodeguide>
    <url>http://thetvdb.com/api/9DAF49C96CBF8DAC/series/267702/all/en.zip</url>
  </episodeguide>
  <episodeguideurl>http://thetvdb.com/api/9DAF49C96CBF8DAC/series/267702/all/en.zip</episodeguideurl>
  <mpaa>TV-14</mpaa>
  <id>267702</id>
  <genre>Action / Crime / Drama / Science-Fiction</genre>
  <premiered>2013-11-17</premiered>
  <studio>FOX</studio>
  <actor>
    <name>Karl Urban</name>
    <role>John Kennex</role>
    <thumb>http://thetvdb.com/banners/actors/312982.jpg</thumb>
  </actor>
  <actor>
    <name>Michael Ealy</name>
    <role>Dorian</role>
    <thumb>http://thetvdb.com/banners/actors/312983.jpg</thumb>
  </actor>
  <actor>
    <name>Lili Taylor</name>
    <role>Captain Sandra Maldonado</role>
    <thumb>http://thetvdb.com/banners/actors/312984.jpg</thumb>
  </actor>
  <actor>
    <name>Michael Irby</name>
    <role>Detective Richard Paul</role>
    <thumb>http://thetvdb.com/banners/actors/312987.jpg</thumb>
  </actor>
  <actor>
    <name>Minka Kelly</name>
    <role>Detective Valerie Stahl</role>
    <thumb>http://thetvdb.com/banners/actors/312986.jpg</thumb>
  </actor>
  <actor>
    <name>Mackenzie Crook</name>
    <role>Rudy Lom</role>
    <thumb>http://thetvdb.com/banners/actors/312985.jpg</thumb>
  </actor>
</tvshow>
```

**Comment by cytec** [comment]
ok, by default it only adds the last 20 entrys to the database, this is to reduce the load of requests, you can however force it to load all data when you enter 0 in the advanced import settings and force the import afterwards...

Also only Files which are listed in the DS DLNA Server get indexed as it querys the DLNAs database for the last x entrys (0 = 999999)

hope this solves your problem...
i know this is kinda tricky but intentionally this whole thing never aimed to load all your data but keep track of your watched/added stuff from now on...

PS: im thinking about a rewrite since a while and maybe when i get some time ill do this (hopefully) a lot has changed (my point of view of what it should do, also as some sort of implementation)

EDIT: *.nfo and tvshow.nfo should be fine also your naming is ok that if it would fail get the correct infos from the filename...

**Comment by demon326** [comment]
Wel, it seems the app still has some issues that needed to be fixed... it gets some movies double, even ads movies that don't make sense, like 'Pooh's Heffalump', not one movie or file name matches that, don't even have 'pooh' in a file name, lol. Also i seems that when i stream over NFS the access log from media server stays empty, not that its your fault. 

So yeah, maybe a beter method should be implented in a future version that does'nt relay on a file or so^^.

Thanks for the help and i keep wachting your git :)

**Comment by cytec** [comment]
yeah ive get some messed up movie names as well, idk what tmdb is doing sometimes :D 
There isn't much you/i can do about it but manually correct the movie (klick it in the webinterface and then hit the edit button (pencil) there you can give a new name to search for and also select from the results)

Yes sadly NFS stream isn't supportet because there is no log file i can check for accessing the file.
DLNA streaming isn't verry accurate either, if you start streaming and then pause it will still count as playing as the log only logs a request and doesn't know if you are playing or not :/

but it works and is still better than manually mark every single episode/movie as seen ;)
